# Generated by Django 4.0.3 on 2022-04-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep_persona',
            name='apellido_casada',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='direccion_residencia',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='rep_persona',
            name='segundo_nombre',
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='dpi',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='REP_INFO_PERSONA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=300)),
                ('segundo_nombre', models.CharField(max_length=350)),
                ('primer_apellido', models.CharField(max_length=300)),
                ('segundo_apellido', models.CharField(max_length=300)),
                ('apellido_casada', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('direccion_residencia', models.CharField(max_length=350)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.rep_persona')),
            ],
            options={
                'verbose_name': 'REP_INFO_PERSONA',
                'verbose_name_plural': 'REP_INFO_PERSONAs',
            },
        ),
    ]
