# Generated by Django 4.0.3 on 2022-04-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_remove_rep_persona_id_persona_alter_rep_persona_dpi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep_persona',
            old_name='oden_cedula',
            new_name='orden_cedula',
        ),
    ]
