# Generated by Django 4.0.3 on 2022-04-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_rename_oden_cedula_rep_persona_orden_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep_trabajo',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rep_empresa',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='REP_VACACIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.rep_trabajo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.rep_persona')),
            ],
            options={
                'verbose_name': 'REP_VACACIONES',
                'verbose_name_plural': 'REP_VACACIONESs',
            },
        ),
    ]
