# Generated by Django 4.0.3 on 2022-04-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_rep_trabajo_status_alter_rep_empresa_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_empresa',
            name='id_empresa',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
