# Generated by Django 4.0.3 on 2022-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_alter_rep_empresa_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_trabajo',
            name='id_trabajo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
