# Generated by Django 4.0.3 on 2022-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0007_alter_rep_trabajo_id_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_trabajo',
            name='salario',
            field=models.FloatField(),
        ),
    ]
