# Generated by Django 4.0.3 on 2022-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0008_alter_rep_trabajo_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_empresa',
            name='codigo',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rep_empresa',
            name='nit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rep_empresa',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='dpi',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='nit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='orden_cedula',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='registro_cedula',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rep_persona',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
